version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./log/grafana:/var/log/grafana
      - ./log/supervisor:/var/log/supervisor
      # /usr/share/grafana/conf/
  graphene:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports: 
      - '2003:2003'
      - '81:80'
    volumes:
      - ./data/graphite:/opt/graphite/storage
      - ./log/graphite:/var/log